name: 'Setup Corda 5 CLI Action'
description: 'Setup Corda 5 CLI and add it to your PATH'
author: 'Manos Batsis'
inputs:
  cli-version:
    required: false
    description: |
      Use a predefined download config for a version already known to the action, e.g. 5.0.0 or 5.1.0
  platform-jars-url:
    required: false
    description: |
      Custom URL for direct download of platform-jars archive. Cannot be combined with cli-version.
      Requires installer-zip-in-archive-path to be set.
      You can find available versions here:
      https://developer.r3.com/next-gen-corda/#get-corda
  installer-zip-in-archive-path:
    required: false
    description: |
      Path of CLI Installer zipfile within the platform jars archive found in platform-jars-url.
      Cannot be combined with cli-version. Requires platform-jars-url to be set.
runs:
  using: 'node16'
  main: 'dist/index.js'