name: 'Setup Corda 5 CLI Action'
description: 'Setup Corda 5 CLI and add it to your PATH'
author: 'Manos Batsis'
inputs:
  cli-version:
    required: false
    description: |
      Use a predefined download config for a version already known to the action, e.g. 5.0.1 or 5.1.0
  cli-installer-zip-url:
    required: false
    description: |
      Url of CLI Installer zipfile (e.g. from Github Releases).
runs:
  using: 'node16'
  main: 'dist/index.js'